apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deployment
  labels:
    app: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb-deployment
  template:
    metadata:
      name: mariadb-deployment
      labels:
        app: mariadb-deployment
    spec:
      containers:
        - name: mariadb-deployment
          image: mariadb:10.5.2
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mariadbsecret
            - name: TZ
              value: Asia/Shanghai
          args:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
          volumeMounts:
            - mountPath: /etc/mysql/mariadb.conf.d
              name: lucasmariadb
            - mountPath: /var/lib/mysql
              name: volume-mariadb
          ports:
            - containerPort: 3307
      restartPolicy: Always
      volumes:
        - name: lucasmariadb
          configMap:
            name: mariadbconfigmap
        - name: volume-mariadb
          persistentVolumeClaim:
            claimName: mariadb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
spec:
  selector:
    app: mariadb-deployment
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3307
      nodePort: 30036
  type: NodePort