server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://lagoucloudeurekaservera:8761/eureka/,http://lagoucloudeurekaserverb:8762/eureka/ #把 eureka 集群中的所有 url 都填写了进来，也可以只写一台，因为各个 eureka server 可以同步注册表
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:1.0-SNAPSHOT
spring:
  application:
    name: lagou-service-user
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 123456

    jpa:
      properties:
        hibernate:
          hbm2ddl:
            auto: create
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
          format_sql: true
      show-sql: true
ribbon:
#请求连接超时时间 #
  ConnectTimeout: 2000 #请求处理超时时间 #
  ReadTimeout: 10000 #对所有操作都进⾏重试
  OkToRetryOnAllOperations: true
