apiVersion: v1
kind: Pod
metadata:
  name: lifecycle
  labels:
    app: lifecycle
spec:
  containers:
    - name: lifecycle
      image: busybox:1.32.0
      imagePullPolicy: IfNotPresent
      command: [ 'sh','-c','sleep 5000' ]
      lifecycle:
        postStart:
          exec:
            command: [ 'mkdir','-p','/lagou/k8s/index.html' ]
  restartPolicy: Always