apiVersion: v1
kind: Pod
metadata:
  name: livenessprob1-test
  labels:
    app: livenessprob1-test
spec:
  containers:
    - name: livenessprob1-test
      image: busybox:1.32.0
      imagePullPolicy: IfNotPresent
      command:
        - '/bin/sh'
        - '-c'
        - 'touch /tmp/liveness; sleep 30; rm -rf /tmp/liveness; sleep 3600;'
      livenessProbe:
        exec:
          command: [ 'test','-e','/tmp/liveness' ]
        initialDelaySeconds: 1
        periodSeconds: 3
      lifecycle:
        preStop:
          exec:
            command: [ 'mkdir','-p','/lagou/k8s/index.html; sleep 30;' ]
  restartPolicy: Always
  