apiVersion: v1
kind: Pod
metadata:
  name: liveness2
  labels:
    app: liveness2
spec:
  containers:
    - name: liveness2
      image: nginx:1.17.10-alpine
      imagePullPolicy: IfNotPresent
      livenessProbe:
        httpGet:
          port: 80
          path: /index.html
        initialDelaySeconds: 3
        timeoutSeconds: 10
  restartPolicy: Always
  